### ISSUE TITLE
index out of bound in curve

### ISSUE THREAD

**Issue by agrignard** [yasushisakai/graphic_studies#1]
Hard to reproduce but i prefer to report it. I found this error after runnign the model for a while. 

I guess it's a very stochastic reason, just to let you know 

![screen shot 2018-09-25 at 12 03 21](https://user-images.githubusercontent.com/3928502/46008361-ccf82800-c0bc-11e8-901d-eccb8d77cf07.png)

**Comment by yasushisakai** [comment]
thanks, fixed it dc98aaed690a5e74f93fd71494f43a99c4c24c86
